site_name: Notes

nav:
  - Home: -index.md
  - Number Systems:
      - Decimal: numbersystems/decimal.md
      - Binary: numbersystems/binary.md
      - Hex: numbersystems/hex.md
  - Types:
      - Int: int.md
      - Char: char.md
      - Float: float.md
      - Double: double.md
  - Data Structures:
      - Overview: datastructures/overview.md
      - Linear Data Structures: datastructures/linear/datastructures_linear.md
      - Linear ADTs: datastructures/linear/ADTs_linear.md
      - Nonlinear ADTs:
          - Binary Search Tree: datastructures/nonlinear/binary_search_tree.md
          - Binary Heap: datastructures/nonlinear/binary_heap.md
          - Skip List: datastructures/nonlinear/skiplist.md
          - Hash Map: datastructures/nonlinear/hashmap.md
          - AVL Tree: datastructures/nonlinear/avl_tree.md
          - (4-2) Tree: datastructures/nonlinear/2-4_tree.md
          - Graph: datastructures/nonlinear/graph.md
  - Algorithms:
      - Big O: algorithms/bigO.md
      - Recursion: algorithms/recursion.md
      - Dynamic Programming: algorithms/dynamic-programming.md
      - Greedy Algorithms: algorithms/greedy-algorithms.md
      - Sorting:
          - General: algorithms/sorting/sorting.md
          - Iterative Sorts:
              - Bubble Sort: algorithms/sorting/iterative_sorts/bubble_sort.md
              - Insertion Sort: algorithms/sorting/iterative_sorts/insertion_sort.md
              - Selection Sort: algorithms/sorting/iterative_sorts/selection_sort.md
          - Divide & Conquer Sorts:
              - Merge Sort: algorithms/sorting/divide_conquer_sorts/merge_sort.md
              - Quick Sort: algorithms/sorting/divide_conquer_sorts/quick_sort.md
              - LSD Radix Sort: algorithms/sorting/divide_conquer_sorts/lsd_radix_sort.md
      - Pattern Matching:
          - General: algorithms/patternmatching/pattern-matching.md
          - Brute force: algorithms/patternmatching/brute_force.md
          - Boyer-Moore: algorithms/patternmatching/boyer-moore.md
          - KMP: algorithms/patternmatching/kmp.md
          - Rabin-Karp: algorithms/patternmatching/rabin_karp.md
      - Graph Algorithms:
          - Graph Search (DFS & BFS): algorithms/graph-algorithms/graph-search-algorithms.md
          - Dijkstra's Algorithm: algorithms/graph-algorithms/dijkstra.md
          - Minimum Spanning Trees: algorithms/graph-algorithms/minimum-spanning-trees.md
  - Languages:
      - Python: languages/python/python.md
      - C:
          - Structs: languages/C/structs.md
          - Pointers: languages/C/pointers.md
          - Arrays: languages/C/arrays.md
          - Strings: languages/C/strings.md
          - Functions: languages/C/functions.md
          - Building Projects: languages/C/building-projects.md
  - Linux:
      - Bash: linux/bash.md
  - DevOps:
      - Processes and Ports: devops/processes_and_ports.md
      - Docker: devops/docker.md
      - Jenkins: devops/jenkins.md
  - Git:
      - General: git.md
      - Git Recipes: git_recipes.md
      - Git-LFS: git_lfs.md
  - Web:
      - General: web/general.md
      - HTML: web/html.md
      - CSS: web/css.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - navigation.top
  # palette:
  # - primary: deep orange
  # - accent: green

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    # text: Palatino Linotype
    text: Raleway
    # code: Cascadia Code PL
    # code: FiraCode Nerd Font Mono
    code: Fira Code
    # code: Ubuntu Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.tabbed
  - meta
  - def_list

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search
